# Generated by Django 3.1.2 on 2020-12-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='django1.jpg', upload_to='profile_pics'),
        ),
    ]
