# Generated by Django 3.1.2 on 2020-12-09 04:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_team_team_image'),
        ('users', '0002_auto_20201207_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9343526371", regex='\\d{10,15}')])),
                ('nationality', models.CharField(default='Indian', max_length=20)),
                ('date_of_birth', models.DateField()),
                ('user_mail_id', models.EmailField(max_length=50)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
