# Generated by Django 3.1.2 on 2020-12-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=50, unique=True)),
                ('team_country', models.CharField(max_length=60, unique=True)),
                ('t_m1', models.TextField(default='player')),
                ('t_m2', models.TextField(default='player')),
                ('t_m3', models.TextField(default='player')),
                ('t_m4', models.TextField(default='player')),
                ('t_m5', models.TextField(default='player')),
                ('t_m6', models.TextField(default='player')),
                ('t_m7', models.TextField(default='player')),
                ('t_m8', models.TextField(default='player')),
                ('t_m9', models.TextField(default='player')),
                ('t_m10', models.TextField(default='player')),
                ('t_m11', models.TextField(default='player')),
            ],
        ),
    ]
