# Generated by Django 3.1.2 on 2020-12-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_image',
            field=models.ImageField(default='django1.jpg', upload_to='team_images/'),
        ),
    ]
