# Generated by Django 3.1.2 on 2020-12-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_team_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='t_m1',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='team',
            name='t_m10',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='team',
            name='t_m11',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='team',
            name='t_m2',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='team',
            name='t_m3',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='team',
            name='t_m4',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='team',
            name='t_m5',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='team',
            name='t_m6',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='team',
            name='t_m7',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='team',
            name='t_m8',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='t_m9',
            field=models.IntegerField(default=11),
        ),
    ]
