# Generated by Django 3.1.2 on 2020-12-10 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20201209_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='t_m1',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='t_m10',
            field=models.OneToOneField(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='player10', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='t_m11',
            field=models.OneToOneField(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='player11', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='t_m2',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='t_m3',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='player3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='t_m4',
            field=models.OneToOneField(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='player4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='t_m5',
            field=models.OneToOneField(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='player5', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='t_m6',
            field=models.OneToOneField(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='player6', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='t_m7',
            field=models.OneToOneField(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='player7', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='t_m8',
            field=models.OneToOneField(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='player8', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='t_m9',
            field=models.OneToOneField(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='player9', to=settings.AUTH_USER_MODEL),
        ),
    ]
