# Generated by Django 3.1.2 on 2020-12-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201210_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_content',
            field=models.TextField(default='International Football Team'),
        ),
    ]
