# Generated by Django 3.1.2 on 2020-12-10 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_team_team_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='point_table',
            fields=[
                ('team_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.team')),
                ('win', models.IntegerField()),
                ('loss', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('played', models.IntegerField()),
            ],
        ),
    ]
