# Generated by Django 3.1.2 on 2020-12-11 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_point_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='stadium',
            fields=[
                ('stadium_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stadium_name', models.CharField(max_length=50, unique=True)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='match',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('match_date', models.DateField()),
                ('stadium_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.stadium')),
                ('teama_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample1', to='blog.team')),
                ('teamb_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample2', to='blog.team')),
            ],
            options={
                'unique_together': {('teama_id', 'teamb_id')},
            },
        ),
        migrations.CreateModel(
            name='goal',
            fields=[
                ('goal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('goal_time', models.TimeField()),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.match')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
