# Generated by Django 3.1.2 on 2020-12-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_goal_match_stadium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
