# Generated by Django 3.1.2 on 2020-12-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201211_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
