# Generated by Django 3.1.2 on 2020-12-12 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_match_match_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='stadium_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.stadium'),
        ),
    ]
