# Generated by Django 3.1.2 on 2020-12-12 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201212_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='team_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.team'),
        ),
    ]
