# Generated by Django 3.1.2 on 2020-12-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_goal_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_date',
            field=models.DateField(default='2020-12-12'),
        ),
    ]
