# Generated by Django 3.1.2 on 2020-12-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_goal_goal_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='t_m1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='t_m10',
        ),
        migrations.RemoveField(
            model_name='team',
            name='t_m11',
        ),
        migrations.RemoveField(
            model_name='team',
            name='t_m2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='t_m3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='t_m4',
        ),
        migrations.RemoveField(
            model_name='team',
            name='t_m5',
        ),
        migrations.RemoveField(
            model_name='team',
            name='t_m6',
        ),
        migrations.RemoveField(
            model_name='team',
            name='t_m7',
        ),
        migrations.RemoveField(
            model_name='team',
            name='t_m8',
        ),
        migrations.RemoveField(
            model_name='team',
            name='t_m9',
        ),
    ]
